language: r

sudo: false

before_install: 
  - sudo apt-get update
  - sudo apt-get -y install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libgdal-dev bwidget libgdal-dev libgdal1-dev libgeos-dev libgeos++-dev libgsl0-dev libproj-dev libspatialite-dev netcdf-bin libgmp3-dev libudunits2-dev cargo

script: make all

cache: packages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: docs
  on:
    branch: master

r_packages:
  - brazilmaps
  - dplyr
  - plyr
  - fs
  - ggplot2
  - glue
  - httr
  - janitor
  - jsonlite
  - magrittr
  - readr
  - rlang
  - rvest
  - sf
  - stringr
  - tidyr
  - tmap
  - xml2
  - gganimate
  - devtools
  - knitr
  - rgdal
  - gifski
  - pkgdown
 
os:
  - linux
