language: r

sudo: false

before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libgdal-dev bwidget libgdal-dev libgdal1-dev libgeos-dev libgeos++-dev libgsl0-dev libproj-dev libspatialite-dev netcdf-bin libgmp3-dev libudunits2-dev cargo

cache: packages

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  keep_history: true
  skip_cleanup: true

after_success:
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'

r_packages:
  - brazilmaps
  - dplyr
  - plyr
  - fs
  - ggplot2
  - glue
  - httr
  - janitor
  - jsonlite
  - magrittr
  - readr
  - rlang
  - rvest
  - sf
  - stringr
  - tidyr
  - tmap
  - xml2
  - gganimate
  - devtools
  - knitr
  - rgdal
  - gifski
  - pkgdown

os:
  - linux
